/*
 * This file is generated by jOOQ.
 */
package com.yg.gqlwfdl.yg.db.public_.tables.records;


import com.yg.gqlwfdl.yg.db.public_.tables.CompanyPartnership;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CompanyPartnershipRecord extends UpdatableRecordImpl<CompanyPartnershipRecord> implements Record3<Long, Long, Long> {

    private static final long serialVersionUID = 2133589125;

    /**
     * Setter for <code>PUBLIC.COMPANY_PARTNERSHIP.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.COMPANY_PARTNERSHIP.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.COMPANY_PARTNERSHIP.COMPANY_A</code>.
     */
    public void setCompanyA(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.COMPANY_PARTNERSHIP.COMPANY_A</code>.
     */
    public Long getCompanyA() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>PUBLIC.COMPANY_PARTNERSHIP.COMPANY_B</code>.
     */
    public void setCompanyB(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.COMPANY_PARTNERSHIP.COMPANY_B</code>.
     */
    public Long getCompanyB() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return CompanyPartnership.COMPANY_PARTNERSHIP.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return CompanyPartnership.COMPANY_PARTNERSHIP.COMPANY_A;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return CompanyPartnership.COMPANY_PARTNERSHIP.COMPANY_B;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getCompanyA();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getCompanyB();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getCompanyA();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getCompanyB();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompanyPartnershipRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompanyPartnershipRecord value2(Long value) {
        setCompanyA(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompanyPartnershipRecord value3(Long value) {
        setCompanyB(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompanyPartnershipRecord values(Long value1, Long value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CompanyPartnershipRecord
     */
    public CompanyPartnershipRecord() {
        super(CompanyPartnership.COMPANY_PARTNERSHIP);
    }

    /**
     * Create a detached, initialised CompanyPartnershipRecord
     */
    public CompanyPartnershipRecord(Long id, Long companyA, Long companyB) {
        super(CompanyPartnership.COMPANY_PARTNERSHIP);

        set(0, id);
        set(1, companyA);
        set(2, companyB);
    }
}
