/*
 * This file is generated by jOOQ.
 */
package com.yg.gqlwfdl.yg.db.public_;


import com.yg.gqlwfdl.yg.db.public_.tables.Company;
import com.yg.gqlwfdl.yg.db.public_.tables.CompanyPartnership;
import com.yg.gqlwfdl.yg.db.public_.tables.Customer;
import com.yg.gqlwfdl.yg.db.public_.tables.DiscountRate;
import com.yg.gqlwfdl.yg.db.public_.tables.PaymentMethod;
import com.yg.gqlwfdl.yg.db.public_.tables.PricingDetails;
import com.yg.gqlwfdl.yg.db.public_.tables.VatRate;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PRIMARY_KEY_6 = Indexes0.PRIMARY_KEY_6;
    public static final Index PRIMARY_KEY_60 = Indexes0.PRIMARY_KEY_60;
    public static final Index PRIMARY_KEY_5 = Indexes0.PRIMARY_KEY_5;
    public static final Index PRIMARY_KEY_B = Indexes0.PRIMARY_KEY_B;
    public static final Index PRIMARY_KEY_D = Indexes0.PRIMARY_KEY_D;
    public static final Index PRIMARY_KEY_8 = Indexes0.PRIMARY_KEY_8;
    public static final Index PRIMARY_KEY_E = Indexes0.PRIMARY_KEY_E;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index PRIMARY_KEY_6 = Internal.createIndex("PRIMARY_KEY_6", Company.COMPANY, new OrderField[] { Company.COMPANY.ID }, true);
        public static Index PRIMARY_KEY_60 = Internal.createIndex("PRIMARY_KEY_60", CompanyPartnership.COMPANY_PARTNERSHIP, new OrderField[] { CompanyPartnership.COMPANY_PARTNERSHIP.ID }, true);
        public static Index PRIMARY_KEY_5 = Internal.createIndex("PRIMARY_KEY_5", Customer.CUSTOMER, new OrderField[] { Customer.CUSTOMER.ID }, true);
        public static Index PRIMARY_KEY_B = Internal.createIndex("PRIMARY_KEY_B", DiscountRate.DISCOUNT_RATE, new OrderField[] { DiscountRate.DISCOUNT_RATE.ID }, true);
        public static Index PRIMARY_KEY_D = Internal.createIndex("PRIMARY_KEY_D", PaymentMethod.PAYMENT_METHOD, new OrderField[] { PaymentMethod.PAYMENT_METHOD.ID }, true);
        public static Index PRIMARY_KEY_8 = Internal.createIndex("PRIMARY_KEY_8", PricingDetails.PRICING_DETAILS, new OrderField[] { PricingDetails.PRICING_DETAILS.ID }, true);
        public static Index PRIMARY_KEY_E = Internal.createIndex("PRIMARY_KEY_E", VatRate.VAT_RATE, new OrderField[] { VatRate.VAT_RATE.ID }, true);
    }
}
