/*
 * This file is generated by jOOQ.
 */
package com.yg.gqlwfdl.yg.db.public_;


import com.yg.gqlwfdl.yg.db.public_.tables.Company;
import com.yg.gqlwfdl.yg.db.public_.tables.CompanyPartnership;
import com.yg.gqlwfdl.yg.db.public_.tables.Customer;
import com.yg.gqlwfdl.yg.db.public_.tables.DiscountRate;
import com.yg.gqlwfdl.yg.db.public_.tables.PaymentMethod;
import com.yg.gqlwfdl.yg.db.public_.tables.PricingDetails;
import com.yg.gqlwfdl.yg.db.public_.tables.VatRate;
import com.yg.gqlwfdl.yg.db.public_.tables.records.CompanyPartnershipRecord;
import com.yg.gqlwfdl.yg.db.public_.tables.records.CompanyRecord;
import com.yg.gqlwfdl.yg.db.public_.tables.records.CustomerRecord;
import com.yg.gqlwfdl.yg.db.public_.tables.records.DiscountRateRecord;
import com.yg.gqlwfdl.yg.db.public_.tables.records.PaymentMethodRecord;
import com.yg.gqlwfdl.yg.db.public_.tables.records.PricingDetailsRecord;
import com.yg.gqlwfdl.yg.db.public_.tables.records.VatRateRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<CompanyRecord, Long> IDENTITY_COMPANY = Identities0.IDENTITY_COMPANY;
    public static final Identity<CompanyPartnershipRecord, Long> IDENTITY_COMPANY_PARTNERSHIP = Identities0.IDENTITY_COMPANY_PARTNERSHIP;
    public static final Identity<CustomerRecord, Long> IDENTITY_CUSTOMER = Identities0.IDENTITY_CUSTOMER;
    public static final Identity<DiscountRateRecord, Long> IDENTITY_DISCOUNT_RATE = Identities0.IDENTITY_DISCOUNT_RATE;
    public static final Identity<PaymentMethodRecord, Long> IDENTITY_PAYMENT_METHOD = Identities0.IDENTITY_PAYMENT_METHOD;
    public static final Identity<PricingDetailsRecord, Long> IDENTITY_PRICING_DETAILS = Identities0.IDENTITY_PRICING_DETAILS;
    public static final Identity<VatRateRecord, Long> IDENTITY_VAT_RATE = Identities0.IDENTITY_VAT_RATE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CompanyRecord> CONSTRAINT_6 = UniqueKeys0.CONSTRAINT_6;
    public static final UniqueKey<CompanyPartnershipRecord> CONSTRAINT_60 = UniqueKeys0.CONSTRAINT_60;
    public static final UniqueKey<CustomerRecord> CONSTRAINT_5 = UniqueKeys0.CONSTRAINT_5;
    public static final UniqueKey<DiscountRateRecord> CONSTRAINT_B = UniqueKeys0.CONSTRAINT_B;
    public static final UniqueKey<PaymentMethodRecord> CONSTRAINT_D = UniqueKeys0.CONSTRAINT_D;
    public static final UniqueKey<PricingDetailsRecord> CONSTRAINT_8 = UniqueKeys0.CONSTRAINT_8;
    public static final UniqueKey<VatRateRecord> CONSTRAINT_E = UniqueKeys0.CONSTRAINT_E;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<CompanyRecord, Long> IDENTITY_COMPANY = Internal.createIdentity(Company.COMPANY, Company.COMPANY.ID);
        public static Identity<CompanyPartnershipRecord, Long> IDENTITY_COMPANY_PARTNERSHIP = Internal.createIdentity(CompanyPartnership.COMPANY_PARTNERSHIP, CompanyPartnership.COMPANY_PARTNERSHIP.ID);
        public static Identity<CustomerRecord, Long> IDENTITY_CUSTOMER = Internal.createIdentity(Customer.CUSTOMER, Customer.CUSTOMER.ID);
        public static Identity<DiscountRateRecord, Long> IDENTITY_DISCOUNT_RATE = Internal.createIdentity(DiscountRate.DISCOUNT_RATE, DiscountRate.DISCOUNT_RATE.ID);
        public static Identity<PaymentMethodRecord, Long> IDENTITY_PAYMENT_METHOD = Internal.createIdentity(PaymentMethod.PAYMENT_METHOD, PaymentMethod.PAYMENT_METHOD.ID);
        public static Identity<PricingDetailsRecord, Long> IDENTITY_PRICING_DETAILS = Internal.createIdentity(PricingDetails.PRICING_DETAILS, PricingDetails.PRICING_DETAILS.ID);
        public static Identity<VatRateRecord, Long> IDENTITY_VAT_RATE = Internal.createIdentity(VatRate.VAT_RATE, VatRate.VAT_RATE.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<CompanyRecord> CONSTRAINT_6 = Internal.createUniqueKey(Company.COMPANY, "CONSTRAINT_6", Company.COMPANY.ID);
        public static final UniqueKey<CompanyPartnershipRecord> CONSTRAINT_60 = Internal.createUniqueKey(CompanyPartnership.COMPANY_PARTNERSHIP, "CONSTRAINT_60", CompanyPartnership.COMPANY_PARTNERSHIP.ID);
        public static final UniqueKey<CustomerRecord> CONSTRAINT_5 = Internal.createUniqueKey(Customer.CUSTOMER, "CONSTRAINT_5", Customer.CUSTOMER.ID);
        public static final UniqueKey<DiscountRateRecord> CONSTRAINT_B = Internal.createUniqueKey(DiscountRate.DISCOUNT_RATE, "CONSTRAINT_B", DiscountRate.DISCOUNT_RATE.ID);
        public static final UniqueKey<PaymentMethodRecord> CONSTRAINT_D = Internal.createUniqueKey(PaymentMethod.PAYMENT_METHOD, "CONSTRAINT_D", PaymentMethod.PAYMENT_METHOD.ID);
        public static final UniqueKey<PricingDetailsRecord> CONSTRAINT_8 = Internal.createUniqueKey(PricingDetails.PRICING_DETAILS, "CONSTRAINT_8", PricingDetails.PRICING_DETAILS.ID);
        public static final UniqueKey<VatRateRecord> CONSTRAINT_E = Internal.createUniqueKey(VatRate.VAT_RATE, "CONSTRAINT_E", VatRate.VAT_RATE.ID);
    }
}
