/*
 * This file is generated by jOOQ.
 */
package com.yg.gqlwfdl.yg.db.public_;


import com.yg.gqlwfdl.yg.db.DefaultCatalog;
import com.yg.gqlwfdl.yg.db.public_.tables.Company;
import com.yg.gqlwfdl.yg.db.public_.tables.CompanyPartnership;
import com.yg.gqlwfdl.yg.db.public_.tables.Customer;
import com.yg.gqlwfdl.yg.db.public_.tables.DiscountRate;
import com.yg.gqlwfdl.yg.db.public_.tables.PaymentMethod;
import com.yg.gqlwfdl.yg.db.public_.tables.PricingDetails;
import com.yg.gqlwfdl.yg.db.public_.tables.VatRate;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -485029911;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.COMPANY</code>.
     */
    public final Company COMPANY = com.yg.gqlwfdl.yg.db.public_.tables.Company.COMPANY;

    /**
     * The table <code>PUBLIC.COMPANY_PARTNERSHIP</code>.
     */
    public final CompanyPartnership COMPANY_PARTNERSHIP = com.yg.gqlwfdl.yg.db.public_.tables.CompanyPartnership.COMPANY_PARTNERSHIP;

    /**
     * The table <code>PUBLIC.CUSTOMER</code>.
     */
    public final Customer CUSTOMER = com.yg.gqlwfdl.yg.db.public_.tables.Customer.CUSTOMER;

    /**
     * The table <code>PUBLIC.DISCOUNT_RATE</code>.
     */
    public final DiscountRate DISCOUNT_RATE = com.yg.gqlwfdl.yg.db.public_.tables.DiscountRate.DISCOUNT_RATE;

    /**
     * The table <code>PUBLIC.PAYMENT_METHOD</code>.
     */
    public final PaymentMethod PAYMENT_METHOD = com.yg.gqlwfdl.yg.db.public_.tables.PaymentMethod.PAYMENT_METHOD;

    /**
     * The table <code>PUBLIC.PRICING_DETAILS</code>.
     */
    public final PricingDetails PRICING_DETAILS = com.yg.gqlwfdl.yg.db.public_.tables.PricingDetails.PRICING_DETAILS;

    /**
     * The table <code>PUBLIC.VAT_RATE</code>.
     */
    public final VatRate VAT_RATE = com.yg.gqlwfdl.yg.db.public_.tables.VatRate.VAT_RATE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Company.COMPANY,
            CompanyPartnership.COMPANY_PARTNERSHIP,
            Customer.CUSTOMER,
            DiscountRate.DISCOUNT_RATE,
            PaymentMethod.PAYMENT_METHOD,
            PricingDetails.PRICING_DETAILS,
            VatRate.VAT_RATE);
    }
}
