/*
 * This file is generated by jOOQ.
 */
package com.yg.gqlwfdl.yg.db.public_;


import com.yg.gqlwfdl.yg.db.DefaultCatalog;
import com.yg.gqlwfdl.yg.db.public_.tables.Company;
import com.yg.gqlwfdl.yg.db.public_.tables.Customer;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 619064557;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.COMPANY</code>.
     */
    public final Company COMPANY = com.yg.gqlwfdl.yg.db.public_.tables.Company.COMPANY;

    /**
     * The table <code>PUBLIC.CUSTOMER</code>.
     */
    public final Customer CUSTOMER = com.yg.gqlwfdl.yg.db.public_.tables.Customer.CUSTOMER;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Company.COMPANY,
            Customer.CUSTOMER);
    }
}
